# -*- coding: utf-8 -*-
"""deployment.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PzoaBjMQNXtVD7cgPthNmp07KDEMMR2T
"""

import matplotlib.pyplot as plt
import streamlit as st
from PIL import Image
from skimage.transform import resize
import cv2
import tensorflow as tf
import matplotlib.pyplot as plt
from tensorflow import keras
import numpy as np
from PIL import Image
import cv2
import numpy as np
from keras.preprocessing import image
model_new=keras.models.load_model('image-classifier-major-project.hdf5')
st.title('Image Classification using transfer learning')
st.sidebar.text('Upload the image')
image_file=st.sidebar.file_uploader('Select your image file',type='jpg')
if image_file is not None:
  file_bytes = np.asarray(bytearray(image_file.read()), dtype=np.uint8)
  opencv_image = cv2.imdecode(file_bytes, 1)
  opencv_image = cv2.cvtColor(opencv_image,cv2.COLOR_BGR2RGB)
  img=Image.open(image_file)
  st.sidebar.image(img,caption='Image uploaded')
  if st.button('Predict'):

     #x=image.load_img('/content/missile3.jpg',target_size=(224,224))
     #plt.imshow(x)
     st.set_option('deprecation.showPyplotGlobalUse', False)
     x = cv2.resize(opencv_image,(224,224))
     from keras.applications.vgg16 import preprocess_input,decode_predictions
     x=np.expand_dims(x,axis=0)
     x = preprocess_input(x)
     y = model_new.predict(x)
     y1=np.ndarray.flatten(y)
     classes=['Space Rocket Ship','fighter jets','missiles']
     percent=[]
     for i in range(len(classes)):
       for k in y1:
         st.sidebar.write(classes[i],(y1[i]*100))
         percent.append(y1[i])
         break
     plt.bar(classes,percent)
     st.pyplot()